name: Run Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  main:
    runs-on: windows-latest
    steps:
      - name: Fetch the sources
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install the dependencies
        shell: pwsh
        run: ./scripts/install.ps1

      - name: Build
        shell: pwsh
        run: ./scripts/build.ps1
